[package]
name = "checkshorturl_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
is-url = "1.0.4"
axum = {version = "0.5.15", features = ["macros"]}
env_logger = "0.9.0"
log = "0.4.17"
serde_json = "1.0"
tokio = {version = "1.21.0", features = ["full"]}
rand = "0.6"