version: "3.8"

services:
  web-server:
    image: nginx
    container_name: 'WebServer'
    volumes:
      - ./web-server:/usr/share/nginx/html # Reactのファイルをマウント
    ports:
      - 7000:80
    restart: always

  reverse-proxy:
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  redis:
    image: redis:7.2.4-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"] # 永続化を有効化
    volumes:
      - redis-data:/data
    restart: always

  rust:
    image: rust:latest
    container_name: rust-environment
    volumes:
      - ./rust-app:/usr/src/myapp
    working_dir: /usr/src/myapp
    command: ["cargo", "run"]
    ports:
      - "7001:7001"
    stdin_open: true
    tty: true

volumes:
  redis-data:
